### PR TITLE
fixed account detail page load issue.

### LINKED ISSUE #161: Missing Account/initialize In App load.
It cause error on Account Detail page.

### PR DESCRIPTION
**Pull request by AnthonyLaw**
### Added
- added account initialize in app load

fixed #161

### CODE REVIEW

File: src/store/index.js [hunk 1]
```diff
@@ -44,22 +44,25 @@ export default new Vuex.Store({
...
+      try { await dispatch('api/initialize') }
         catch (e) { console.error('Failed to initialize API', e) }
-        
-      try { await dispatch('block/initialize') } 
+
+      try { await dispatch('block/initialize') }
+        catch (e) { console.error('Failed to initialize block', e) }
+
+      try { await dispatch('account/initialize') }
         catch (e) { console.error('Failed to initialize block', e) }
```
Comment (OlegMakarenko) [inline src/store/index.js]: block => account

Comment (AnthonyLaw) [reply src/store/index.js]: my bad. will change it now.
